blank_issues_enabled: false
contact_links:
  - name: Horizen Community Support Help Desk
    url:https://horizenofficial.atlassian.net/servicedesk/customer/portals
    about: Please ask your questions regarding support here.
